---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://chucknorris-eureka-elb-407449240.eu-west-1.elb.amazonaws.com/eureka/

---
spring:
  profiles: IT
facts: Chuck Norris can delete the Recycling Bin.;Chuck Norris can unit test entire applications with a single assert.;Chuck Norris writes code that optimizes itself.
  
---
spring:
  profiles: SCIENCE
facts: Chuck Norris doesn't breathe air. He holds air hostage.;Chuck Norris will never have a heart attack. His heart isn't nearly foolish enough to attack him.

---
spring:
  profiles: GYM
words: When Chuck Norris works out he doesn't get stronger, the machine does.
