---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://chucknorris-eureka-elb-407449240.eu-west-1.elb.amazonaws.com/eureka/

---
spring:
  profiles: IT
facts: 
  
---
spring:
  profiles: SCIENCE
facts: 

---
spring:
  profiles: GYM
words: 
